import { readFileSync, statSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { defineConfig, type Plugin } from "vitest/config";

// The GitHub Pages base path is injected by the deploy workflow via
// VITE_BASE so the same bundle works at `/`, `/notes/`, or any subpath.
const base = process.env.VITE_BASE ?? "/";

const pkg = JSON.parse(
  readFileSync(new URL("./package.json", import.meta.url), "utf8"),
) as { version: string };

// Short build identifier surfaced next to the header wordmark and in the
// update prompt so you can tell at a glance which build is running. Shape:
// `<pkg.version>[.<run>][+<commit>]` — `<run>` is the GitHub Actions run
// number (omitted locally), `<commit>` the short SHA as build metadata.
const GITHUB_RUN_NUMBER = process.env.GITHUB_RUN_NUMBER;
const COMMIT_HASH = (process.env.GITHUB_SHA ?? "").slice(0, 7);
const BUILD_LABEL =
  pkg.version +
  (GITHUB_RUN_NUMBER ? `.${GITHUB_RUN_NUMBER}` : "") +
  (COMMIT_HASH ? `+${COMMIT_HASH}` : "");

// Workbox precache cache id. A stable, app-specific id keeps this app's
// precache cache (`<cacheId>-precache-v2-<scope>`) distinct on a shared
// Pages origin; the download-progress tracker in `usePwaUpdate` opens this
// cache by name to measure install progress. Must stay in sync with
// `CACHE_ID` in `src/pwa/usePwaUpdate.ts`.
const CACHE_ID = "notes";

// Emit `dist/version.json` so the still-active old service worker can tell
// the client which version is incoming when a new build deploys (read
// cache-bypassed by `usePwaUpdate` on the workbox `waiting` event).
function emitVersionJson(): Plugin {
  return {
    name: "emit-version-json",
    apply: "build",
    generateBundle() {
      this.emitFile({
        type: "asset",
        fileName: "version.json",
        source: JSON.stringify({ version: BUILD_LABEL }) + "\n",
      });
    },
  };
}

// Emit a `precache-manifest.json` listing every precached asset and its
// byte size so `usePwaUpdate` can render a real download-progress fill
// (it sums the bytes of cached entries against this total). Runs in
// `closeBundle`, after VitePWA (`enforce: "post"`) has written `dist/sw.js`
// with the workbox precache list inlined.
function emitPrecacheManifest(): Plugin {
  return {
    name: "emit-precache-manifest",
    apply: "build",
    enforce: "post",
    closeBundle() {
      const distDir = fileURLToPath(new URL("./dist/", import.meta.url));
      let sw: string;
      try {
        sw = readFileSync(`${distDir}sw.js`, "utf8");
      } catch {
        // No SW emitted (e.g. PWA disabled) — nothing to summarise.
        return;
      }
      // vite-plugin-pwa inlines the workbox precache list as
      // `self.__WB_MANIFEST` resolved to `[{url, revision}, ...]`.
      const urls = new Set<string>();
      for (const m of sw.matchAll(/"(?:revision":[^}]*?)?url":"([^"]+)"/g)) {
        if (m[1]) urls.add(m[1]);
      }
      for (const m of sw.matchAll(/url:"([^"]+)"/g)) {
        if (m[1]) urls.add(m[1]);
      }
      const assets: Record<string, number> = {};
      let totalBytes = 0;
      for (const url of urls) {
        const clean = url.split("?")[0] ?? url;
        const path = clean.startsWith("/") ? clean.slice(1) : clean;
        try {
          const size = statSync(`${distDir}${path}`).size;
          assets[clean.startsWith("/") ? clean : `/${clean}`] = size;
          totalBytes += size;
        } catch {
          // Listed in the manifest but absent on disk — skip it.
        }
      }
      writeFileSync(
        `${distDir}precache-manifest.json`,
        JSON.stringify({ totalBytes, assets }) + "\n",
      );
    },
  };
}

export default defineConfig({
  base,
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // `UpdateToast` registers the SW itself via `workbox-window` (so it
      // can pass `updateViaCache: "none"`) and the new build parks in the
      // `waiting` state until the user clicks Reload — no silent swap, no
      // auto-injected `<script>`.
      registerType: "prompt",
      injectRegister: null,
      includeAssets: [
        "favicon.svg",
        "favicon.ico",
        "apple-touch-icon-180x180.png",
      ],
      manifest: {
        id: base,
        scope: base,
        start_url: base,
        name: "Notes",
        short_name: "Notes",
        description:
          "A local-first PWA for taking notes that works great on mobile and desktop.",
        theme_color: "#1f2933",
        background_color: "#1f2933",
        display: "standalone",
        orientation: "any",
        lang: "en",
        categories: ["productivity", "utilities"],
        // Generated by `make icons` from `public/favicon.svg`; see
        // `pwa-assets.config.ts`. Keep in sync with the PNGs under `public/`.
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        cacheId: CACHE_ID,
        // Precache the app shell: JS, CSS, fonts, icons, and the HTML
        // entry. Source maps stay on the network.
        globPatterns: ["**/*.{js,css,html,svg,png,ico,webp,woff2}"],
        globIgnores: ["**/*.map"],
        cleanupOutdatedCaches: true,
        // Serve the precached app shell for any in-scope navigation so the
        // app opens offline / on a deep link. The data JSON files are read
        // cache-bypassed by `usePwaUpdate`, so keep them off the fallback.
        navigateFallback: `${base}index.html`,
        navigateFallbackDenylist: [
          /version\.json$/,
          /precache-manifest\.json$/,
        ],
      },
    }),
    emitVersionJson(),
    emitPrecacheManifest(),
  ],
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
    __BUILD_LABEL__: JSON.stringify(BUILD_LABEL),
  },
  test: {
    // Domain/storage tests run in node. UI tests opt into jsdom with a
    // `// @vitest-environment jsdom` docblock at the top of the file.
    environment: "node",
    globals: true,
    include: ["tests/**/*.test.{ts,tsx}"],
  },
});
