// Packaging config for the desktop wrapper.
//
// A `.cjs` config rather than the usual `electron-builder.yml` so it can read
// the app's real version out of the root `package.json` — `electron/` keeps
// its own manifest and nothing bumps it, so a download named after that would
// claim a number no release ever had.
//
// ARCHIVES, not installers, on every platform. An installer is a promise this
// project cannot keep unsigned: an unsigned NSIS setup trips SmartScreen and
// an un-notarized DMG is refused outright by Gatekeeper. A zip/tar.gz has
// neither problem and is what someone who wants a portable copy actually
// wants — installers come back as an addition once signing credentials exist,
// not as a fix.

const { version } = require("../package.json");

/**
 * WHO SIGNS THE macOS BUILD — and why an UNSIGNED one is not an option.
 *
 * Apple Silicon does not merely distrust unsigned arm64 code, it refuses to
 * EXECUTE it, and macOS reports that to the user as "Notes.app is damaged" —
 * the same wording it uses for a corrupt download. So the mac build always
 * signs, and the only question is with what: a real Developer ID certificate
 * when `CSC_LINK` / `CSC_NAME` provide one (with `APPLE_ID` and friends set,
 * electron-builder notarizes on the way out and Gatekeeper stays quiet), and
 * AD HOC (`identity: "-"`) otherwise. An ad-hoc signature satisfies the
 * kernel — the app runs natively — but it is nobody's identity, so the first
 * launch still needs one trip through System Settings › Privacy & Security.
 * That is a prompt a user can answer; "damaged" is not.
 *
 * An ad-hoc signature cannot be timestamped (there is no certificate for a
 * timestamp to outlive) and `codesign` fails outright if asked for one, so
 * the timestamp is switched off on that path only.
 */
const MAC_IDENTITY =
  process.env.CSC_LINK || process.env.CSC_NAME ? undefined : "-";
const MAC_ADHOC = MAC_IDENTITY === "-";

/** Shared with the mobile wrapper (native/app.json) — one identity for the
 * app wherever it ships. */
const BUNDLE_ID = "se.niclaslindstedt.notes";

/** What the executable is called where it is a COMMAND: one lowercase word. */
const EXECUTABLE_NAME = "notes";

/** The 512px PWA icon is the only artwork the app has; electron-builder
 * converts it to each platform's format. Regenerated by `make icons`. */
const ICON = "../public/pwa-512x512.png";

module.exports = {
  appId: BUNDLE_ID,
  productName: "Notes",
  copyright: `Copyright © ${new Date().getFullYear()} Niclas Lindstedt`,

  directories: { output: "release" },

  // Spelled out rather than left to the per-target defaults so every download
  // reads the same way and carries its platform and architecture on its face.
  artifactName: `${EXECUTABLE_NAME}-\${version}-\${os}-\${arch}.\${ext}`,

  // The app's version, not the shell package's (see the note at the top).
  extraMetadata: { version },

  // Everything the app is, and nothing else: the main process and the built
  // web app. `../src` is NOT here — it was compiled into `webroot/` already.
  files: ["main.js", "webroot/**/*", "package.json"],

  // The shell draws no chrome of its own, so Chromium's other locales are
  // tens of megabytes of UI strings nothing ever asks it to render.
  electronLanguages: ["en"],

  asar: true,

  win: {
    executableName: EXECUTABLE_NAME,
    icon: ICON,
    target: [{ target: "zip", arch: "x64" }],
  },

  mac: {
    icon: ICON,
    category: "public.app-category.productivity",
    // Both slices as separate artifacts rather than one universal binary, so
    // neither download carries a copy of Chromium the machine will never run.
    target: [
      { target: "zip", arch: "x64" },
      { target: "zip", arch: "arm64" },
    ],
    // NEVER unsigned — an unsigned arm64 app cannot run at all. See
    // MAC_IDENTITY above for what each value means and what the user sees.
    identity: MAC_IDENTITY,
    ...(MAC_ADHOC ? { timestamp: "none", notarize: false } : {}),
    hardenedRuntime: true,
    gatekeeperAssess: false,
  },

  linux: {
    executableName: EXECUTABLE_NAME,
    icon: ICON,
    category: "Utility",
    target: [{ target: "tar.gz", arch: "x64" }],
  },
};
